# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [1]:
import sys
print("Python location:", sys.executable)
print("Python version:", sys.version)

Python location: /home/seanwong/miniconda3/envs/pds/bin/python
Python version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]


In [2]:
import numpy as np
my_arr = np.arange(1_000_000) #np.arange creates a numPy array with values from 0 to 999,999
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

NumPy Vectorized Multiplication (my_arr * 2):
1.36 ms ± 122 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
58.6 ms ± 4.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Interpretation of results: 1.36ms v 58.6ms: NumPy operation approximately 30 times faster than the python list operation

## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [4]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

print(f"Array 1:\n{arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}, Dimensions: {arr1.ndim}")

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 1:
[6.  7.5 8.  0.  1. ]
Shape: (5,), Dtype: float64, Dimensions: 1
Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


In [5]:
jagged_data = [
    [1, 2, 3],
    [4, 5]
]

#jagged_arr = np.array[jagged_data]
jagged_arr_obj = np.array(jagged_data, dtype=object)
print(f"Jagged Array (dtype=object):\n(jagged_arr_obj)")
print(f"Shape: {jagged_arr_obj.shape}, Dtype: {jagged_arr_obj.dtype}, Dimensions: {jagged_arr_obj.ndim}")

Jagged Array (dtype=object):
(jagged_arr_obj)
Shape: (2,), Dtype: object, Dimensions: 1


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [6]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [25]:
# Your code here
one_array = np.ones((3,4)) #create 3x4 array of all ones
one_array.astype(np.float32) # cast to float32

str_arr = np.array(['1.25', '-9.6', '42'])
float_arr = str_arr.astype(float)

print("Original string array", str_arr)
print("Casted to float32:", float_arr)

Original string array ['1.25' '-9.6' '42']
Casted to float32: [ 1.25 -9.6  42.  ]


#common mistakes: 
str_array = np.array([-1.25', '-9.6', 'not_a_number]) #casting will raise a value error due to conversion cannot change to float

## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [26]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [27]:
print("Adding scalar 10 to array (arr + 10):\n", arr + 10)

Adding scalar 10 to array (arr + 10):
 [[11. 12. 13.]
 [14. 15. 16.]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [28]:
# [DEMO] Slicing views
# note that slicing mutates the original array, as it creates a view, not a copy
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing - slice row then column
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [48]:
# Your code here
arr2d[:, 0]
arr2d[1, :] = 0
print("\nSet all values second row to 0:\n", arr2d)

print("Shape & dimension of arr2d[1]:", arr2d[1].shape, "&", arr2d[1].ndim)
print("Shape & dimension of arr2d[1,:]:", arr2d[1,:].shape, "&", arr2d[1,:].ndim)
print("Shape & dimension of arr2d[1,:2]:", arr2d[1:2,:].shape, "&", arr2d[1:2,:].ndim)


Set all values second row to 0:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]
Shape & dimension of arr2d[1]: (3,) & 1
Shape & dimension of arr2d[1,:]: (3,) & 1
Shape & dimension of arr2d[1,:2]: (1, 3) & 2


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [49]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [ ]:
# 1. Select all scores where name is not 'Bob'
bob_unmask = (names != 'Bob')
print("Unmask:", bob_unmask)
print("Everyone else's scores:\n", scores[bob_unmask])

#2 select scores for 'Bob'or 'Will'using the | operator
bob_or_will_mask = (names == 'Bob') | (names == 'Will')
print("Bob or Will mask:", bob_or_will_mask)
print("Bob or Will's scores:\n", scores[bob_or_will_mask])

#3 scores less than 80 and set to 0
scores[scores < 80] = 0
print("Scores with values less than 80 set to 0:\n", scores)


Unmask: [False  True  True False  True  True  True]
Everyone else's scores:
 [[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [  0  80]]
Bob or Will mask: [ True False  True  True  True False False]
Bob or Will's scores:
 [[  0  80]
 [ 95 100]
 [100   0]
 [ 85  92]]
Scores with values less than 80 set to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [59]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [[-0.42226784 -0.06741235  1.01293176 -0.02190373]
 [-0.62156784 -0.26118369 -1.07356164 -0.44887756]
 [-0.15508894 -0.4803072  -1.11677771 -1.19316792]]

Mean down rows (axis=0): [-0.39964154 -0.26963441 -0.39246919 -0.55464974]
Sum across columns (axis=1): [ 0.50134785 -2.40519073 -2.94534177]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [60]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [ ]:
# Your code here
reshaped_arr = np.arange(15).reshape((3,5))
print("Reshaped array:\n", reshaped_arr)

row_means = reshaped_arr.mean(axis=1)
print("Row means:", row_means)

sample_array = np.array([[1, 2], [3, 4], [5, 6]])
distinct_elements = np.unique(sample_array)
print("Distinct elements in sample_array:", distinct_elements)

#transpose reshaped array
transposed_arr = reshaped_arr.T
print("Transposed array:\n", transposed_arr)

Reshaped array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Row means: [ 2.  7. 12.]
Distinct elements in sample_array: [1 2 3 4 5 6]
Transposed array:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
